# Configuration pour Account Service
spring:
  application:
    name: account-service
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/microservices_db
    username: postgres
    password: admin123
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 600000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: pportnet@gmail.com
    password: pfji scip qsrp sspi
    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
  web:
    resources:
      static-locations: file:${user.profile.photo.upload-dir}/
  main:
    allow-circular-references: true

# Configuration spécifique Account Service
server:
  port: 8085

# Configuration des uploads - Path corrigé
user:
  profile:
    photo:
      upload-dir: "C:/Users/moham/OneDrive/Desktop/New folder/backend_pfe/backend_pfe/account-service/src/main/resources/user-photos"

# Configuration Frontend
app:
  frontend:
    url: http://localhost:5174

# Configuration Logging spécifique
logging:
  level:
    com.portnet.accountservice: DEBUG
