# Configuration pour Gateway Service
spring:
  cloud:
    discovery:
      enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # Routes pour Incident Service
        - id: incident-service-commentaires
          uri: lb://incident-service
          predicates:
            - Path=/api/commentaires/**

        - id: incident-service-incidents
          uri: lb://incident-service
          predicates:
            - Path=/api/incidents/**

        - id: incident-service-plans-action
          uri: lb://incident-service
          predicates:
            - Path=/api/plans-action/**

        - id: incident-service-taches
          uri: lb://incident-service
          predicates:
            - Path=/api/taches/**

        # Routes pour Account Service
        - id: account-service-auth
          uri: lb://account-service
          predicates:
            - Path=/auth/**

        - id: account-service-profile
          uri: lb://account-service
          predicates:
            - Path=/profile/**

        - id: account-service-users
          uri: lb://account-service
          predicates:
            - Path=/users/**

        - id: account-service-admin
          uri: lb://account-service
          predicates:
            - Path=/admin/**

        - id: account-service-membres
          uri: lb://account-service
          predicates:
            - Path=/api/membres/**

server:
  port: 8888

# Configuration Eureka - hérite de application.yml
eureka:
  instance:
    prefer-ip-address: true

logging:
  level:
    com.example.gatewayservice: DEBUG
    org.springframework.cloud.gateway: DEBUG