spring:
  application:
    name: gateway-service
  cloud:
    discovery:
      enabled: true
    gateway:
      routes:
        - id: incident-commentaires
          uri: lb://INCIDENT-SERVICE
          predicates:
            - Path=/api/commentaires/**
        - id: incident-incidents
          uri: lb://INCIDENT-SERVICE
          predicates:
            - Path=/api/incidents/**
        - id: incident-plans-action
          uri: lb://INCIDENT-SERVICE
          predicates:
            - Path=/api/plans-action/**
        - id: incident-taches
          uri: lb://INCIDENT-SERVICE
          predicates:
            - Path=/api/taches/**
        - id: account-profile
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/profile/**
        - id: gateway-auth
          uri: lb://GATEWAY-SERVICE
          predicates:
            - Path=/auth/**
        - id: account-public-profile
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/public-profile/**
        - id: account-users
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/users/**
        - id: account-register
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/register/**
server:
  port: 8888
jwt:
  secret: TmJLS8mnj7T81MOKdTIy/NZ5NzXl3JCfJNFw8+eK3meb/hcM02FNZApHxRJv+Z75ss2H4u8RjZdxJdFKbfyDog==
  expiration: 86400000 # Durée de validité du token en millisecondes (ici, 1 jour)
  header: Authorization
  prefix: Bearer
app:
  account-service:
    url: http://ACCOUNT-SERVICE
