# Configuration pour Incident Service
spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/incident_service_db
    username: postgres
    password: admin123
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 600000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      INDENT_OUTPUT: true

server:
  port: 8082

# Configuration Eureka - hérite de application.yml
eureka:
  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework.security: DEBUG
    com.example.incidentservice: DEBUG
