spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/incidentsdb
    username: postgres
    password: oumaima
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      INDENT_OUTPUT: true

server:
  port: 8082

jwt:
  secret: c2VjcmV0S2V5Rm9ySldUMTIzNDU2Nzg5MDEyMzQ1Ng==  # secretKeyForJWT1234567890123456 en Base64
  expiration: 86400000  # 1 jour en ms

logging:
  level:
    org.springframework.security: DEBUG
